language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

env:
  global:
    - TRAVIS_EXT_HOME=$HOME/travis-ext
    - TRAVIS_EXT=$$TRAVIS_EXT_HOME/travis-ext.sh
    - PROJECT_LANGUAGE=android

before_install:
  - git clone --depth=50 --branch=develop https://github.com/westmisfit/travis-ext.git $HOME/travis-ext
  - scripts/test.sh
  - $TRAVIS_EXT install_infer

script:
  - ./gradlew assembleDebug

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.gradle
    - $HOME/.gradle
